<div class="content lesspadding">
	<p>
		&copy; {{ site.time | date: "%Y" }} Juan C. M&uuml;ller<br/>
		The source of this site can be found at<a href="http://github.com/jcmuller/jcmuller.github.com/">
		GitHub</a>
	</p>
</div>

<div class="browsers-note">
	This site renders as intended in
	<img src="/images/firefox.png" alt="Mozilla Firefox" height="16" width="16" />
	<img src="/images/chrome.png" alt="Google Chrome" height="16" width="16" />
	<img src="/images/safari.png" alt="Safari" height="16" width="16" />
	<img src="/images/opera.png" alt="Opera" height="16" width="16" />.
	I don't really care about
	<img src="/images/ie.png" alt="IE" height="16" width="16" />.
</div>

