<h1>
			{{ site.title }}
			<div class="profiles">
				<a href="http://twitter.com/juancmuller">     <img src="/images/twitter.png"   /></a>
				<a href="https://github.com/jcmuller">        <img src="/images/github.png"    /></a>
				<a href="http://facebook.com/juan.muller">    <img src="/images/facebook.png"  /></a>
				<a href="http://www.linkedin.com/in/mullerjc"><img src="/images/linkedin.png"  /></a>
				<a href="http://delicious.com/sputnik82">     <img src="/images/delicious.png" /></a>
			</div>
		</h1>
		<h3><a href="{{ site.blog }}">Home</a></h3>
		{% if page.title %}<div class="content lesspadding">
			<h2>{{ page.title }}</h2>
		</div>{% endif %}
